[graph]
all-features = true

[advisories]
ignore = [
    # curve25519-dalek vulnerability
    "RUSTSEC-2024-0344",

    # derivative unmaintained warning
    "RUSTSEC-2024-0388",

    # openssl vulnerability
    "RUSTSEC-2025-0004",

    "RUSTSEC-2022-0093", # ed25519-dalek 1.0.1

    # ring vulnerability - coming from Solana dependencies
    "RUSTSEC-2025-0009",

    # protobuf issue
    "RUSTSEC-2024-0437",

    # paste
    "RUSTSEC-2024-0436",

    # humantime -- unmaintened
    # "RUSTSEC-2025-0014",

]
